### ISSUE TITLE
support authentication for extension endpoints

### ISSUE THREAD

**Issue by ryancurrah** [jaimeteb/chatto#11]
Currently extensions do not have support authentication. This is insecure. We should add support for setting an auth token.

**Comment by jaimeteb** [comment]
So for example, a `bot.yml` file would look like this?:

```
bot_name: "trivia_bot"
extensions:
  type: REST
  url: http://localhost:8770
  token: my-extensions-token
```

And `extension.ServeREST` should check for the token in all calls, right?
