### ISSUE TITLE
ability to transition from multiple states

### ISSUE THREAD

**Issue by ryancurrah** [jaimeteb/chatto#17]
Add ability to transition `from` multiple states not just `any`.

```
functions:
  - transition:
      from:
        - "gomodules"
        - "goreleaser"
      into: "initial"
    command: "thanks"
    message:
      - text: ":thumbsup: no problem-o"
```
