### ISSUE TITLE
automatically get states and commands from transitions

### ISSUE THREAD

**Issue by ryancurrah** [jaimeteb/chatto#36]
We could make the `fsm.yml` configuration easier by determining the `states` and `commands` automatically from the `transitions`. It would be a matter of looping the `transitions` to enumerate each automatically. Below is an example `fsm.yml` with the proposed changes from the `01_test` example.

```yaml
initial_state: "off"

transitions:
  - from:
      - "off"
    into: "on"
    command: "turn_on"
    message: 
      - text: "Turning on."

  - from:
      - "on"
    into: "off"
    command: "turn_off"
    message:
      - text: "Turning off."
      - text: "❌"

  - from:
      - "any"
    into: "off"
    command: "hello_universe"
    extension: "any"

defaults:
  unknown: "Can't do that."
  unsure: "???"
  error: "Error"
```
